export const WHITELIST = new Set([
    "google.com", "www.google.com",
    "facebook.com", "www.facebook.com",
    "youtube.com", "www.youtube.com",
    "twitter.com", "www.twitter.com",
    "instagram.com", "www.instagram.com",
    "linkedin.com", "www.linkedin.com",
    "amazon.com", "www.amazon.com",
    "microsoft.com", "www.microsoft.com",
    "apple.com", "www.apple.com",
    "wikipedia.org", "www.wikipedia.org",
    "yahoo.com", "www.yahoo.com",
    "netflix.com", "www.netflix.com",
    "github.com", "www.github.com",
    "stackoverflow.com", "www.stackoverflow.com",
    "reddit.com", "www.reddit.com",
    "bing.com", "www.bing.com",
    "live.com", "www.live.com",
    "twitch.tv", "www.twitch.tv",
    "myshopify.com",
    "zoom.us", "www.zoom.us",
    "dropbox.com", "www.dropbox.com",
    "paypal.com", "www.paypal.com"
]);
